export default {
  media_inset: false,
  cards: [
    {
      title: "Take Inventory",
      eyebrow: "April 2024",
      subhead: "",
      container_classes: "wave-card usa-dark-background",
      media: {
        media_classes: "",
        image_classes: "",
        image_src: "https://picsum.photos/307/200",
        image_alt_text: "A placeholder image",
      },
      content: "Take photos and videos of household items and valuables.",
      cta: {
        link: "https://google.com",
        link_target: "",
        button_label: "Steps to prepare for a flood",
        button_type: "default",
        button_markup: "link",
        button_inverse: true,
        button_alignment: "left",
        icon_id: "",
      },
    },
    {
      title: "Check Paperwork",
      eyebrow: "April 2024",
      subhead: "",
      container_classes: "wave-card usa-dark-background",
      media: {
        media_classes: "",
        image_classes: "",
        image_src: "https://picsum.photos/307/200",
        image_alt_text: "A placeholder image",
      },
      content:
        "Check your mortgage agreement for flood insurance requirements. Check your mortgage agreement for flood insurance requirements.",
      cta: {
        link: "https://google.com",
        link_target: "",
        button_label: "Learn about insurance requirements",
        button_type: "default",
        button_markup: "link",
        button_inverse: true,
        button_alignment: "left",
        icon_id: "",
      },
    },
    {
      title: "Waterproof",
      eyebrow: "April 2024",
      subhead: "",
      container_classes: "wave-card usa-dark-background",
      media: {
        media_classes: "",
        image_classes: "",
        image_src: "https://picsum.photos/307/200",
        image_alt_text: "A placeholder image",
      },
      content: "Waterproof your basement and elevate your utilities",
      cta: {
        link: "https://google.com",
        link_target: "",
        button_label: "How to minimize damage",
        button_type: "default",
        button_markup: "link",
        button_inverse: true,
        button_alignment: "left",
        icon_id: "",
      },
    },
  ],
};
